# A simple example of ClusterConfig object:
# IMPORTANT NOTES on extended release. Extended release is very expensive (6xs normal rate). Need to avoid this if possible.
# Right now standard release as of 11/2024 is 1.28 1.29 1.30 1.31
# https://docs.aws.amazon.com/eks/latest/userguide/disable-extended-support.html
# https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
# This should be ok as the major revision occurred around 1.23 
# See the version below. I have edited it to 1.29
# EOL dates for 1.28 Nov 26, 2024; 1.29 March 23,2025; 1.30 July 23, 2025; 1.31 Nov 26, 2025
# Use the 1.29
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  #name: cluster-dave
  name: cluster-ansible
  #region: us-west-1
  region: us-east-1
  #version: "1.26" 
  version: "1.29" 

nodeGroups:
  - name: ng-2
    #instanceType: t3.large
    instanceType: t3.small
    desiredCapacity: 3
