- name: add docker prune to crontab
  ansible.builtin.cron:
    name: docker prune
    minute: "01"
    hour: "4"
    user: root
    job: "docker system prune --all --force > /dev/null 2>&1"
#this will be run after all of the other cronjobs
